### ISSUE TITLE
Citing AutoFPGA

### ISSUE THREAD

**Issue by m-kru** [ZipCPU/autofpga#4]
Is there any publication on AutoFPGA that one can cite in papers, or anything else that you would like one to reference except GitHub autofpga url?

**Comment by ZipCPU** [comment]
The articles about  [AutoFPGA](https://github.com/ZipCPU/AutoFPGA) are all posted on the [ZipCPU blog](https://zipcpu.com).  You can find their links in the [main README.md file](https://github.com/ZipCPU/AutoFPGA/blob/master/README.md) for [AutoFPGA](https://github.com/ZipCPU/AutoFPGA).  Perhaps [this is the best introductory article](https://zipcpu.com/zipcpu/2017/10/05/autofpga-intro.html) of them all, even though it is a bit dated.
